### ISSUE TITLE
How to apply to 2D medical images

### ISSUE THREAD

**Issue by Masaaki-75** [function2-llx/PUMIT#6]
Hi. I am trying to apply the pre-trained model on the 2D CT slices and I am not sure how to determine the input format.

In my case, each 2D slice is already extracted and the original 3D volume is unavailable (I guess the metadata doesn't help much here), so I forced `aniso_d==6` (implying z-spacing to be infinity?) and found that the network sucessfully runs. But if I determined the `aniso_d` with `patch_size==(1, 16, 16)`, the network raises error, as in the following snippet:
```Python
# vit = ViT(
#         in_channels=3,
#         patch_size=16, 
#         embed_dim=768,
#         pos_embed_shape=[5, 10, 10], 
#         pretrained_pos_embed_shape = [16, 16],
#         pretrained_ckpt = Checkpoint(),
#     )

x = torch.randn((512, 512)).clamp(-1, 1).float()  # represents a normalized CT slice
x_torch = x.reshape(1, 1, 1, 512, 512).repeat_interleave(3, dim=1)  # make it [B, 3, 1, H, W] to meet the input requirement

x_spat = SpatialTensor(x_torch, aniso_d=6)  # force it to be 6
feats = vit(x_spat).as_tensor()  # this works fine
# feat.shape: (1, 1025, 768), 
# feat.min(): (tensor(-6.3774, grad_fn=<MinBackward1>), 
# feat.max(): tensor(5.5557, grad_fn=<MaxBackward1>)).

patch_size = (1, 16, 16)  # [d, h, w]
aniso_d = max(0, bin(16 // patch_size[0]).count("1") - 1)  # equiv to .bit_count()
x_spat2 = SpatialTensor(x_torch, aniso_d=aniso_d)
feats = vit(x_spat2).as_tensor()  # raise RuntimeError
```

The error messages are like:
```
...
File ..., in ViT.forward_features(self, x)
  283 def forward_features(self, x: torch.Tensor): 
--> 284 x, shape = self.prepare_seq_input(x) 
  285 self.rope.prepare(shape)
      ...
-> 1142 ret = func(*args, **kwargs) 
  1143 if func in get_default_nowrap_functions(): 
  1144     return ret 

RuntimeError: Calculated padded input size per channel: (1 x 512 x 512). Kernel size: (16 x 16 x 16). Kernel size can't be greater than actual input size
```

You also used 2D data to train your network. Could you share some insights on how to deal with 2D slices? Thanks!

**Comment by function2-llx** [comment]
Hello, the variable `aniso_d` is corresponds to the "degree of anisotropy (DA)" in the paper, which is defined to be log_2 (spacing_z / spacing_xy), so setting it to 6 will be enough for 2D images.
As for calculating `aniso_d` from the patch size, you should use `bit_length` instead of `bit_count`. I think it is a bug in: https://github.com/function2-llx/PUMIT/blob/35ebe8afcc23dc8a40a1830f39716fea89363004/pumit/model/adapter.py#L21
However, it happens not to affect the downstream segmentation experiments, since we always use a patch size of (4, 16, 16), while the largest feature map output by the adapter has 1/4 of the original resolution.

**Comment by Masaaki-75** [comment]
Now it works fine for me. Thanks for the clarification!
